SELECT * FROM customer_shopping.customer; 

use customer_shopping;

-- What is the total revenue generated by male vs female customers?

select gender , SUM(purchase_amount) as revenue 
from customer 
group by gender;

-- Which customers used a discount but still spent more than the average purchase amount?

select customer_id , purchase_amount 
from customer
where discount_applied = 'Yes' and 
purchase_amount >= (select AVG(purchase_amount) from customer);

-- Which are top 5 products with highest average review ratings?

select item_purchased, round(avg(review_rating), 2) as "Average Revirew Rating" 
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Compare the average purchase amount between Standard and Express Shipping.

select shipping_type, round(avg(purchase_amount),2) as "Average Purchase amount"
from customer
where shipping_type in ("Standard", "Express")
group by shipping_type;

-- Do subcribers spend more? Compare the average spend and total revenue between subcribers and non-subcribers.

select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as average_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by average_spend, total_revenue desc;

-- Which 5 products have the highest percentage of purchase with discount applied?

select item_purchased, 
round(sum(case when discount_applied = 'Yes' then 1 else 0 end) /count(*) * 100,2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;


-- Segment the customers into 'New', 'Returning' and  'Loyal' based on their total unmber of previous purchases.
-- Show the count of each segmments

with customer_segment as(
select customer_id, previous_purchases,
case
	when previous_purchases = 1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal' 
    end as customer_type
from customer
)

select customer_type, count(*) as 'Number of Customers'
from customer_segment
group by customer_type


-- What  are the top 3 most purchased products in each category?

with item_counts as(
select category, item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <=3;


-- Are customers who are repeat buyers (more than 5 previous purchases) are likly to be subcribers?

select subscription_status, count(customer_id) as previous_buyers
from customer
where previous_purchases > 5
group by subscription_status;


-- What is the revenue contribution of each age group?

select age_group, sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;


